### ISSUE TITLE
Rust - Web Framework

### ISSUE THREAD

**Issue by explooosion** [ghost-Island-program-last-hope/Plan#6]
### 07/28
**時間： 14:00~18:00**
**主題： Rust - 網站伺服器**
**講者： 共同導讀**

- 使用框架 [actix-web](https://github.com/actix/actix-web) - 開始活躍
- 其他框架 [Rocket](https://github.com/SergioBenitez/Rocket) - 維護率下降

### 教材 

- 英文網站 [Actix](https://actix.rs/)
- 中文網站 [Actix](https://actix-cn.github.io/)

### 基礎知識

- [Rust 程序设计语言（第二版） 简体中文版](https://kaisery.gitbooks.io/trpl-zh-cn/content/)

**Comment by explooosion** [comment]
```toml
[dependencies] 
actix-web = { version="^0.7", features=["tls", "alpn", "brotli", "flate2-c", "flate2-rust"], default-features = false }
```
